name: free-the-bugs
base: core22
version: '0.5.1'
summary: A short game on fixing java bugs
description: |
  Was initially made for mehu game jam in just 2 days! Itch link: https://ragebreaker.itch.io/free-the-bugs

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  free-the-bugs:
    command: free-the-bugs
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - network
      - opengl
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - unity7
    desktop: gui/free-the-bugs.desktop

parts:
  free-the-bugs:
    plugin: dump
    source: ./builds/
    source-type: local
    stage-packages:
      - libglu1-mesa
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxi6
      - libpulse0
    override-build: |
      snapcraftctl build
      chmod +x $SNAPCRAFT_PART_INSTALL/free-the-bugs

layout:
  /usr/share/free-the-bugs:
    bind: $SNAP/usr/share/free-the-bugs
